apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: node-exporter
    name: node-exporter
  name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      name: node-exporter
  template:
    metadata:
      labels:
        name: node-exporter
      name: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter
        args: ["--collector.textfile.directory", "/node-exporter-textfile"]
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
        volumeMounts:
          - name: textfile
            mountPath: /node-exporter-textfile
      hostNetwork: true
      hostPID: true
      volumes:
        - name: textfile
          hostPath:
            path: /var/run/node-exporter-textfile