apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
{{ include "kconmon.app.labels.standard" . | indent 4 }}
  name: controller-pdb-percentage
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: kconmon
      component: controller
