apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
{{ include "kconmon.app.labels.standard" . | indent 4 }}
  name: kconmon
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
