apiVersion: v1
kind: ConfigMap
metadata:
  name: ping-exporter-config
  namespace: prometheus
data:
  targets.json: |
    {"cluster_targets":[{"ipAddress":"10.0.1.122","name":"10.0.1.122-1a"},{"ipAddress":"10.0.1.165","name":"10.0.1.165-1a"},{"ipAddress":"10.0.3.229","name":"10.0.3.229-1c"}],"external_targets":[{"host":"8.8.8.8","name":"google-dns"},{"host":"youtube.com"}]}